sudo: false
language: node_js
node_js:
  - "5"
  - "6"
  - "7"
  - "8"
  - "node"

addons:
  chrome: stable
  firefox: latest

script:
  - npm test
  - npm run lint
  - npm run browser-test

git:
  depth: 1
  submodules: false

cache:
  directories:
    - "node_modules"
