language: node_js
node_js:
  - "5"
  - "6"
  - "7"
  - "8"
  - "node"

sudo: false
script:
  - npm test
  - npm run lint

git:
  depth: 1
  submodules: false

cache:
  directories:
    - "node_modules"
